service: books-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-bundle
  - serverless-offline

functions:
  getBooks:
    handler: getBooks.handler
    events:
      - http:
          path: /books
          method: GET
          cors: true
